name: Publish Docker - Codgital

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run the action on"
        default: "main"
        required: true

jobs:
  build_and_publish_platform_containers:
    name: Build and publish platform containers
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        platform: [amd64, arm64]
        app:
          - name: unsend
            dockerfile: ./docker/Dockerfile
            context: .
          - name: smtp-proxy
            dockerfile: ./apps/smtp-server/Dockerfile
            context: ./apps/smtp-server

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the docker image
        env:
          BUILD_PLATFORM: ${{ matrix.platform }}
          APP: ${{ matrix.app.name }}
          DOCKER_FILE: ${{ matrix.app.dockerfile }}
          CONTEXT: ${{ matrix.app.context }}
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          GHCR_USER: ${{ github.repository_owner }}
        run: |
          APP_VERSION="$(git name-rev --tags --name-only $(git rev-parse HEAD) | head -n 1 | sed 's/\^0//')"
          GIT_SHA="$(git rev-parse HEAD)"

          docker build \
            -f "$DOCKER_FILE" \
            --progress=plain \
            -t "$DOCKERHUB_USER/$APP-$BUILD_PLATFORM:latest" \
            -t "$DOCKERHUB_USER/$APP-$BUILD_PLATFORM:$GIT_SHA" \
            -t "$DOCKERHUB_USER/$APP-$BUILD_PLATFORM:$APP_VERSION" \
            -t "ghcr.io/$GHCR_USER/$APP-$BUILD_PLATFORM:latest" \
            -t "ghcr.io/$GHCR_USER/$APP-$BUILD_PLATFORM:$GIT_SHA" \
            -t "ghcr.io/$GHCR_USER/$APP-$BUILD_PLATFORM:$APP_VERSION" \
            "$CONTEXT"

      - name: Push the docker image to DockerHub
        run: docker push --all-tags "${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.app.name }}-${{ matrix.platform }}"
        
      - name: Push the docker image to GitHub Container Registry
        run: docker push --all-tags "ghcr.io/${{ github.repository_owner }}/${{ matrix.app.name }}-${{ matrix.platform }}"


  create_and_publish_manifest:
    name: Create and publish manifest
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: build_and_publish_platform_containers
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push DockerHub manifest
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          APP_VERSION="$(git name-rev --tags --name-only $(git rev-parse HEAD) | head -n 1 | sed 's/\^0//')"
          GIT_SHA="$(git rev-parse HEAD)"

          for APP_NAME in unsend smtp-proxy; do
            docker manifest create \
              $DOCKERHUB_USER/$APP_NAME:latest \
              --amend $DOCKERHUB_USER/$APP_NAME-amd64:latest \
              --amend $DOCKERHUB_USER/$APP_NAME-arm64:latest

            docker manifest create \
              $DOCKERHUB_USER/$APP_NAME:$GIT_SHA \
              --amend $DOCKERHUB_USER/$APP_NAME-amd64:$GIT_SHA \
              --amend $DOCKERHUB_USER/$APP_NAME-arm64:$GIT_SHA

            docker manifest create \
              $DOCKERHUB_USER/$APP_NAME:$APP_VERSION \
              --amend $DOCKERHUB_USER/$APP_NAME-amd64:$APP_VERSION \
              --amend $DOCKERHUB_USER/$APP_NAME-arm64:$APP_VERSION

            docker manifest push $DOCKERHUB_USER/$APP_NAME:latest
            docker manifest push $DOCKERHUB_USER/$APP_NAME:$GIT_SHA
            docker manifest push $DOCKERHUB_USER/$APP_NAME:$APP_VERSION
          done

      - name: Create and push GitHub Container Registry manifest
        env:
          GHCR_USER: ${{ github.repository_owner }}
        run: |
          APP_VERSION="$(git name-rev --tags --name-only $(git rev-parse HEAD) | head -n 1 | sed 's/\^0//')"
          GIT_SHA="$(git rev-parse HEAD)"

          for APP_NAME in unsend smtp-proxy; do
            docker manifest create \
              ghcr.io/$GHCR_USER/$APP_NAME:latest \
              --amend ghcr.io/$GHCR_USER/$APP_NAME-amd64:latest \
              --amend ghcr.io/$GHCR_USER/$APP_NAME-arm64:latest

            docker manifest create \
              ghcr.io/$GHCR_USER/$APP_NAME:$GIT_SHA \
              --amend ghcr.io/$GHCR_USER/$APP_NAME-amd64:$GIT_SHA \
              --amend ghcr.io/$GHCR_USER/$APP_NAME-arm64:$GIT_SHA

            docker manifest create \
              ghcr.io/$GHCR_USER/$APP_NAME:$APP_VERSION \
              --amend ghcr.io/$GHCR_USER/$APP_NAME-amd64:$APP_VERSION \
              --amend ghcr.io/$GHCR_USER/$APP_NAME-arm64:$APP_VERSION

            docker manifest push ghcr.io/$GHCR_USER/$APP_NAME:latest
            docker manifest push ghcr.io/$GHCR_USER/$APP_NAME:$GIT_SHA
            docker manifest push ghcr.io/$GHCR_USER/$APP_NAME:$APP_VERSION
          done